export interface Challenge {
  question: string;
  options: string[];
  answer: number;
}

type ChallengeBank = Record<string, Record<string, Challenge[]>>;

export const challengeBank: ChallengeBank = {
  python: {
    beginner: [
      { question: "What keyword declares a variable in Python?", options: ["var", "let", "x =", "dim"], answer: 2 },
      { question: "Which operator adds two numbers?", options: ["+", "&", "||", ">>"], answer: 0 },
      { question: "How do you print in Python?", options: ["echo()", "console.log()", "print()", "System.out"], answer: 2 },
      { question: "What is 10 % 3?", options: ["3", "1", "0", "10"], answer: 1 },
      { question: "Which is a boolean value?", options: ['"yes"', "1.5", "True", "None"], answer: 2 },
      { question: "What does type() return?", options: ["Value", "Data type", "Length", "Nothing"], answer: 1 },
      { question: "Which is a comment in Python?", options: ["// text", "/* text */", "# text", "-- text"], answer: 2 },
      { question: "What is 2 ** 3?", options: ["6", "8", "9", "5"], answer: 1 },
      { question: "Which creates a string?", options: ["123", "'hello'", "[1,2]", "{a:1}"], answer: 1 },
      { question: "What does int('5') return?", options: ["'5'", "5.0", "5", "Error"], answer: 2 },
      { question: "How to get user input?", options: ["scan()", "input()", "read()", "get()"], answer: 1 },
      { question: "Which is NOT a data type?", options: ["int", "str", "loop", "float"], answer: 2 },
    ],
    basic: [
      { question: "What does len() return?", options: ["Type", "Length", "Last item", "Sum"], answer: 1 },
      { question: "How to define a function?", options: ["func", "def", "function", "fn"], answer: 1 },
      { question: "Which creates a list?", options: ["()", "{}", "[]", "<>"], answer: 2 },
      { question: "What is 'hello'[1]?", options: ["h", "e", "l", "o"], answer: 1 },
      { question: "How to handle errors?", options: ["try/except", "if/else", "for/in", "while"], answer: 0 },
      { question: "What does .append() do?", options: ["Remove", "Add to end", "Sort", "Copy"], answer: 1 },
      { question: "Which loop iterates a list?", options: ["while", "do-while", "for...in", "switch"], answer: 2 },
      { question: "What does range(5) produce?", options: ["1-5", "0-4", "0-5", "1-4"], answer: 1 },
      { question: "How to check type?", options: ["typeof()", "type()", "check()", "is()"], answer: 1 },
      { question: "What does .split() do?", options: ["Join strings", "Split to list", "Cut string", "Remove chars"], answer: 1 },
      { question: "Which is a dictionary?", options: ["[1,2]", "(1,2)", "{1:2}", "<1,2>"], answer: 2 },
      { question: "What does 'return' do?", options: ["Print", "Exit function with value", "Loop", "Import"], answer: 1 },
    ],
    medium: [
      { question: "What is O(n log n)?", options: ["Linear", "Quadratic", "Linearithmic", "Constant"], answer: 2 },
      { question: "Which is immutable?", options: ["List", "Dict", "Set", "Tuple"], answer: 3 },
      { question: "What does __init__ do?", options: ["Delete", "Initialize", "Import", "Export"], answer: 1 },
      { question: "What is polymorphism?", options: ["One form", "Many forms", "No form", "Base form"], answer: 1 },
      { question: "Stack uses which principle?", options: ["FIFO", "LIFO", "Random", "Priority"], answer: 1 },
      { question: "What is recursion?", options: ["Loop", "Self-calling fn", "Import", "Class"], answer: 1 },
      { question: "Binary search needs?", options: ["Any list", "Sorted list", "Linked list", "Empty list"], answer: 1 },
      { question: "What is a lambda?", options: ["Class", "Anonymous fn", "Module", "Variable"], answer: 1 },
      { question: "What does map() do?", options: ["Create dict", "Apply fn to items", "Navigate", "Sort"], answer: 1 },
      { question: "List comprehension creates?", options: ["Tuple", "Dict", "New list", "Set"], answer: 2 },
      { question: "What is encapsulation?", options: ["Hiding data", "Looping", "Printing", "Sorting"], answer: 0 },
      { question: "Queue uses which principle?", options: ["LIFO", "FIFO", "Random", "Stack"], answer: 1 },
    ],
    advanced: [
      { question: "What is a decorator?", options: ["Class", "Function wrapper", "Variable", "Module"], answer: 1 },
      { question: "GIL stands for?", options: ["Global Int Lock", "Global Interpreter Lock", "Gen Int Lock", "None"], answer: 1 },
      { question: "What is memoization?", options: ["Memory alloc", "Caching results", "Threading", "Logging"], answer: 1 },
      { question: "REST uses which protocol?", options: ["FTP", "HTTP", "SSH", "SMTP"], answer: 1 },
      { question: "What is Big O of hash lookup?", options: ["O(1)", "O(n)", "O(log n)", "O(n²)"], answer: 0 },
      { question: "What is a closure?", options: ["Loop", "Fn + scope", "Class", "Error"], answer: 1 },
      { question: "What pattern is Observer?", options: ["Creational", "Structural", "Behavioral", "None"], answer: 2 },
      { question: "What is a generator?", options: ["Class", "Lazy iterator", "Loop", "Module"], answer: 1 },
      { question: "What does yield do?", options: ["Return + pause", "Exit", "Import", "Delete"], answer: 0 },
      { question: "What is monkey patching?", options: ["Testing", "Runtime modification", "Debugging", "Logging"], answer: 1 },
      { question: "What is metaclass?", options: ["Class of class", "Subclass", "Interface", "Module"], answer: 0 },
      { question: "async/await is for?", options: ["Sync code", "Async code", "Testing", "Types"], answer: 1 },
    ],
  },
  javascript: {
    beginner: [
      { question: "Which keyword declares a constant?", options: ["var", "let", "const", "def"], answer: 2 },
      { question: "What is typeof 42?", options: ["'int'", "'number'", "'float'", "'digit'"], answer: 1 },
      { question: "How to log to console?", options: ["print()", "echo()", "console.log()", "log()"], answer: 2 },
      { question: "What is === in JS?", options: ["Assignment", "Loose equal", "Strict equal", "Not equal"], answer: 2 },
      { question: "Which is falsy?", options: ["1", "'0'", "null", "[]"], answer: 2 },
      { question: "How to create array?", options: ["()", "{}", "[]", "<>"], answer: 2 },
      { question: "Template literal uses?", options: ["' '", "\" \"", "` `", "/ /"], answer: 2 },
      { question: "What does NaN mean?", options: ["Null", "Not a Number", "No answer", "None"], answer: 1 },
      { question: "How to write a comment?", options: ["# text", "// text", "-- text", "** text"], answer: 1 },
      { question: "What is undefined?", options: ["Null", "No value assigned", "Zero", "Error"], answer: 1 },
    ],
    basic: [
      { question: "Arrow function syntax?", options: ["=>", "->", ">>", "~>"], answer: 0 },
      { question: "Which method adds to array end?", options: ["unshift", "push", "append", "add"], answer: 1 },
      { question: "What does .map() return?", options: ["Boolean", "New array", "Number", "Object"], answer: 1 },
      { question: "How to destructure?", options: ["let {a} = obj", "let a = obj.a", "Both work", "Neither"], answer: 2 },
      { question: "What is spread operator?", options: ["...", "***", "---", ":::"], answer: 0 },
      { question: "JSON.parse() does?", options: ["To string", "To object", "To array", "To number"], answer: 1 },
      { question: "What is Promise?", options: ["Loop", "Async wrapper", "Class", "Error"], answer: 1 },
      { question: "What does .filter() do?", options: ["Sort items", "Keep matching items", "Remove all", "Count"], answer: 1 },
      { question: "Event listener method?", options: ["on()", "addEventListener()", "listen()", "bind()"], answer: 1 },
      { question: "What is 'this' in JS?", options: ["Current scope", "Global only", "Context object", "Class name"], answer: 2 },
    ],
    medium: [
      { question: "What is event bubbling?", options: ["Events go up DOM", "Events go down", "Events stop", "Events repeat"], answer: 0 },
      { question: "What is a closure?", options: ["Loop", "Fn + outer scope", "Class", "Module"], answer: 1 },
      { question: "Prototypal inheritance means?", options: ["Class-based", "Object-based chain", "No inheritance", "Interface"], answer: 1 },
      { question: "What does async/await do?", options: ["Sync code", "Handle promises", "Create threads", "Parse JSON"], answer: 1 },
      { question: "WeakMap holds?", options: ["Strong refs", "Weak refs", "No refs", "Circular refs"], answer: 1 },
      { question: "What is hoisting?", options: ["Moving vars to top", "Deleting vars", "Copying vars", "Sorting vars"], answer: 0 },
      { question: "Symbol is for?", options: ["Unique keys", "Math ops", "String ops", "Array ops"], answer: 0 },
      { question: "What is debouncing?", options: ["Delay execution", "Speed up", "Cancel all", "Repeat"], answer: 0 },
    ],
    advanced: [
      { question: "What is a Proxy?", options: ["Server", "Object interceptor", "Cache", "Router"], answer: 1 },
      { question: "What is tree shaking?", options: ["Removing dead code", "Sorting", "Caching", "Minifying"], answer: 0 },
      { question: "What is a Web Worker?", options: ["Background thread", "Service worker", "DOM helper", "Cache API"], answer: 0 },
      { question: "What is Reflect API?", options: ["Mirror objects", "Meta-programming", "DOM API", "Math API"], answer: 1 },
      { question: "Generator function uses?", options: ["return", "yield", "await", "throw"], answer: 1 },
      { question: "What is tail call optimization?", options: ["Loop opt", "Recursive opt", "Memory opt", "Speed opt"], answer: 1 },
      { question: "SharedArrayBuffer is for?", options: ["Shared memory", "Shared DOM", "Shared CSS", "Shared HTML"], answer: 0 },
      { question: "What is V8?", options: ["JS engine", "CSS engine", "HTML parser", "Server"], answer: 0 },
    ],
  },
  java: {
    beginner: [
      { question: "Java is which type?", options: ["Scripting", "Compiled + Interpreted", "Markup", "Query"], answer: 1 },
      { question: "Main method signature?", options: ["void main()", "public static void main(String[])", "int main()", "def main()"], answer: 1 },
      { question: "Print in Java?", options: ["print()", "console.log()", "System.out.println()", "echo()"], answer: 2 },
      { question: "Which is a primitive?", options: ["String", "int", "Integer", "Array"], answer: 1 },
      { question: "How to declare array?", options: ["int[]", "array<int>", "[int]", "int()"], answer: 0 },
      { question: "What is JVM?", options: ["Compiler", "Virtual Machine", "IDE", "Library"], answer: 1 },
      { question: "Which keyword creates object?", options: ["create", "new", "init", "make"], answer: 1 },
      { question: "String is?", options: ["Primitive", "Object", "Array", "Interface"], answer: 1 },
    ],
    basic: [
      { question: "What is inheritance keyword?", options: ["inherits", "extends", "implements", "uses"], answer: 1 },
      { question: "Interface uses which keyword?", options: ["extends", "implements", "inherits", "uses"], answer: 1 },
      { question: "What is encapsulation?", options: ["Hiding internals", "Looping", "Sorting", "Printing"], answer: 0 },
      { question: "ArrayList vs Array?", options: ["Same", "ArrayList is dynamic", "Array is dynamic", "Neither"], answer: 1 },
      { question: "What does 'final' mean?", options: ["Last item", "Cannot change", "End of file", "Static"], answer: 1 },
      { question: "try-catch handles?", options: ["Loops", "Exceptions", "Input", "Output"], answer: 1 },
      { question: "What is a constructor?", options: ["Destructor", "Init method", "Loop", "Import"], answer: 1 },
      { question: "What is 'static'?", options: ["Instance level", "Class level", "Private", "Final"], answer: 1 },
    ],
    medium: [
      { question: "What is abstraction?", options: ["Hiding complexity", "Adding code", "Debugging", "Testing"], answer: 0 },
      { question: "HashMap key must be?", options: ["Mutable", "Immutable/hashable", "String only", "Int only"], answer: 1 },
      { question: "What is polymorphism?", options: ["One form", "Many forms", "No form", "Static form"], answer: 1 },
      { question: "Garbage collection does?", options: ["Compile code", "Free unused memory", "Sort data", "Cache data"], answer: 1 },
      { question: "What is a thread?", options: ["Process", "Lightweight process", "Memory", "Cache"], answer: 1 },
      { question: "What is an enum?", options: ["Variable", "Constant set", "Array", "Map"], answer: 1 },
    ],
    advanced: [
      { question: "What is reflection?", options: ["Runtime type inspection", "Compilation", "Debugging", "Testing"], answer: 0 },
      { question: "What are generics?", options: ["Type parameters", "Variables", "Methods", "Classes"], answer: 0 },
      { question: "Stream API is for?", options: ["File I/O", "Functional data processing", "Networking", "Threading"], answer: 1 },
      { question: "What is a lambda in Java?", options: ["Class", "Anonymous function", "Variable", "Package"], answer: 1 },
      { question: "What is CompletableFuture?", options: ["Sync", "Async composition", "Thread", "Lock"], answer: 1 },
      { question: "JIT compilation means?", options: ["Ahead of time", "Just in time", "Never", "Manual"], answer: 1 },
    ],
  },
  sql: {
    beginner: [
      { question: "SQL stands for?", options: ["Structured Query Language", "Simple Query Language", "Standard Query Logic", "System Query Language"], answer: 0 },
      { question: "Select all columns?", options: ["SELECT ALL", "SELECT *", "SELECT COLUMNS", "GET *"], answer: 1 },
      { question: "Filter rows with?", options: ["FILTER", "WHERE", "HAVING", "IF"], answer: 1 },
      { question: "Sort results with?", options: ["SORT BY", "ORDER BY", "GROUP BY", "ARRANGE"], answer: 1 },
      { question: "Insert data with?", options: ["ADD INTO", "INSERT INTO", "PUT INTO", "PUSH INTO"], answer: 1 },
      { question: "Delete rows with?", options: ["REMOVE", "DELETE FROM", "DROP", "ERASE"], answer: 1 },
      { question: "Update data with?", options: ["MODIFY", "CHANGE", "UPDATE", "ALTER"], answer: 2 },
      { question: "Which joins all matching?", options: ["LEFT JOIN", "RIGHT JOIN", "INNER JOIN", "CROSS JOIN"], answer: 2 },
    ],
    basic: [
      { question: "GROUP BY is used with?", options: ["WHERE", "Aggregate functions", "ORDER BY", "LIMIT"], answer: 1 },
      { question: "COUNT() returns?", options: ["Sum", "Number of rows", "Average", "Max"], answer: 1 },
      { question: "DISTINCT removes?", options: ["Nulls", "Duplicates", "Errors", "Columns"], answer: 1 },
      { question: "LIKE '%abc' matches?", options: ["Starts with abc", "Ends with abc", "Contains abc", "Exact abc"], answer: 1 },
      { question: "NULL check uses?", options: ["= NULL", "IS NULL", "== NULL", "NULL()"], answer: 1 },
      { question: "LIMIT does what?", options: ["Filter rows", "Restrict results count", "Sort", "Group"], answer: 1 },
    ],
    medium: [
      { question: "Subquery is?", options: ["Nested query", "Main query", "View", "Trigger"], answer: 0 },
      { question: "What is normalization?", options: ["Reducing redundancy", "Adding data", "Deleting tables", "Sorting"], answer: 0 },
      { question: "Index improves?", options: ["Insert speed", "Query speed", "Delete speed", "Update speed"], answer: 1 },
      { question: "What is a VIEW?", options: ["Table copy", "Virtual table", "Index", "Trigger"], answer: 1 },
      { question: "HAVING filters?", options: ["Rows", "Groups", "Columns", "Tables"], answer: 1 },
      { question: "What is a foreign key?", options: ["Primary key copy", "Reference to another table", "Index", "View"], answer: 1 },
    ],
    advanced: [
      { question: "What is a CTE?", options: ["Common Table Expression", "Create Table Entity", "Column Type Extension", "Cross Table Entity"], answer: 0 },
      { question: "Window functions use?", options: ["GROUP BY", "OVER()", "WHERE", "HAVING"], answer: 1 },
      { question: "ACID stands for?", options: ["Atomicity Consistency Isolation Durability", "Add Create Insert Delete", "All Columns In Database", "Auto Commit Insert Data"], answer: 0 },
      { question: "What is a stored procedure?", options: ["Saved query", "Table", "Column type", "Index"], answer: 0 },
      { question: "Deadlock is?", options: ["Fast query", "Circular wait", "Index scan", "Table lock"], answer: 1 },
    ],
  },
  c: {
    beginner: [
      { question: "C was created by?", options: ["James Gosling", "Dennis Ritchie", "Guido van Rossum", "Bjarne Stroustrup"], answer: 1 },
      { question: "Entry point in C?", options: ["start()", "main()", "init()", "run()"], answer: 1 },
      { question: "Print in C?", options: ["print()", "echo()", "printf()", "console.log()"], answer: 2 },
      { question: "Which is integer type?", options: ["float", "char", "int", "string"], answer: 2 },
      { question: "Header for I/O?", options: ["<io.h>", "<stdio.h>", "<input.h>", "<print.h>"], answer: 1 },
      { question: "Pointer stores?", options: ["Value", "Address", "Type", "Size"], answer: 1 },
      { question: "Which ends a statement?", options: [".", ":", ";", ","], answer: 2 },
      { question: "sizeof() returns?", options: ["Value", "Address", "Bytes of type", "Length"], answer: 2 },
      { question: "Array index starts at?", options: ["1", "0", "-1", "Depends"], answer: 1 },
      { question: "Which is a loop?", options: ["if", "switch", "while", "return"], answer: 2 },
    ],
    basic: [
      { question: "Pointer declaration?", options: ["int *p", "int &p", "int p*", "ptr int p"], answer: 0 },
      { question: "What does malloc() do?", options: ["Free memory", "Allocate memory", "Copy memory", "Print memory"], answer: 1 },
      { question: "struct creates?", options: ["Function", "Custom type", "Array", "Loop"], answer: 1 },
      { question: "What does free() do?", options: ["Allocate", "Deallocate memory", "Copy", "Print"], answer: 1 },
      { question: "String in C is?", options: ["Class", "Char array", "Object", "Struct"], answer: 1 },
      { question: "scanf() is for?", options: ["Output", "Input", "File I/O", "Math"], answer: 1 },
      { question: "What is NULL?", options: ["Zero", "Empty pointer", "String", "Error"], answer: 1 },
      { question: "What does #include do?", options: ["Import header", "Define var", "Create fn", "Loop"], answer: 0 },
    ],
    medium: [
      { question: "What is segfault?", options: ["Syntax error", "Invalid memory access", "Type error", "Logic error"], answer: 1 },
      { question: "Linked list node has?", options: ["Data only", "Data + pointer", "Pointer only", "Index"], answer: 1 },
      { question: "What is stack overflow?", options: ["Array full", "Too much recursion", "Null pointer", "Type error"], answer: 1 },
      { question: "What does typedef do?", options: ["Create var", "Create type alias", "Delete type", "Cast type"], answer: 1 },
      { question: "File pointer type?", options: ["FILE*", "file_t", "int*", "void*"], answer: 0 },
      { question: "Bitwise AND operator?", options: ["&&", "&", "||", "|"], answer: 1 },
    ],
    advanced: [
      { question: "What is volatile?", options: ["Constant", "May change externally", "Static", "Private"], answer: 1 },
      { question: "Function pointer syntax?", options: ["int (*fp)()", "int *fp()", "fn *fp", "ptr fp()"], answer: 0 },
      { question: "What is memory leak?", options: ["Fast alloc", "Unreleased memory", "Stack overflow", "Null access"], answer: 1 },
      { question: "Union vs struct?", options: ["Same", "Union shares memory", "Struct shares", "No diff"], answer: 1 },
      { question: "What is DMA?", options: ["Direct Memory Access", "Data Management", "Debug Mode", "Driver"], answer: 0 },
      { question: "Preprocessor runs?", options: ["At runtime", "Before compilation", "After linking", "During debug"], answer: 1 },
    ],
  },
  "c++": {
    beginner: [
      { question: "C++ adds what to C?", options: ["HTML", "OOP", "SQL", "CSS"], answer: 1 },
      { question: "Output in C++?", options: ["printf()", "cout <<", "print()", "echo()"], answer: 1 },
      { question: "Input in C++?", options: ["scanf()", "cin >>", "input()", "read()"], answer: 1 },
      { question: "Namespace for std?", options: ["use std", "using namespace std", "import std", "#include std"], answer: 1 },
      { question: "Which is a reference?", options: ["int *x", "int &x", "int x[]", "ref int x"], answer: 1 },
      { question: "Header for I/O?", options: ["<stdio.h>", "<iostream>", "<input>", "<io>"], answer: 1 },
      { question: "Bool values are?", options: ["0/1", "true/false", "yes/no", "Both A and B"], answer: 3 },
      { question: "String class header?", options: ["<text>", "<string>", "<str>", "<chars>"], answer: 1 },
    ],
    basic: [
      { question: "Class access default?", options: ["public", "private", "protected", "friend"], answer: 1 },
      { question: "Inheritance keyword?", options: ["extends", ":", "implements", "inherits"], answer: 1 },
      { question: "What is a constructor?", options: ["Destructor", "Object initializer", "Static fn", "Friend fn"], answer: 1 },
      { question: "Destructor prefix?", options: ["!", "~", "-", "#"], answer: 1 },
      { question: "Vector is in?", options: ["<array>", "<vector>", "<list>", "<container>"], answer: 1 },
      { question: "Template keyword?", options: ["generic", "template", "type", "auto"], answer: 1 },
      { question: "What is 'auto'?", options: ["Automatic type", "Auto loop", "Auto import", "Auto class"], answer: 0 },
      { question: "new keyword does?", options: ["Delete", "Heap allocation", "Stack alloc", "Copy"], answer: 1 },
    ],
    medium: [
      { question: "Virtual function enables?", options: ["Static binding", "Dynamic binding", "No binding", "Early binding"], answer: 1 },
      { question: "What is RAII?", options: ["Random Access", "Resource Acquisition Is Initialization", "Runtime API", "Read Access"], answer: 1 },
      { question: "Smart pointer type?", options: ["raw_ptr", "unique_ptr", "safe_ptr", "auto_ptr"], answer: 1 },
      { question: "What is operator overloading?", options: ["Redefine operators", "Delete operators", "Create operators", "Import operators"], answer: 0 },
      { question: "STL stands for?", options: ["Standard Template Library", "System Type Library", "Static Template Logic", "Standard Type List"], answer: 0 },
      { question: "Abstract class has?", options: ["No methods", "Pure virtual fn", "Only static", "No members"], answer: 1 },
    ],
    advanced: [
      { question: "Move semantics use?", options: ["&&", "&", "*", "**"], answer: 0 },
      { question: "What is SFINAE?", options: ["Error type", "Template trick", "Memory model", "Thread model"], answer: 1 },
      { question: "constexpr means?", options: ["Constant", "Compile-time eval", "Runtime const", "Extern const"], answer: 1 },
      { question: "What are variadic templates?", options: ["Fixed args", "Variable args", "No args", "One arg"], answer: 1 },
      { question: "What is a mutex?", options: ["Data type", "Mutual exclusion lock", "Memory unit", "Template"], answer: 1 },
      { question: "Lambda capture [=] means?", options: ["By reference", "By value", "Nothing", "Move"], answer: 1 },
    ],
  },
  typescript: {
    beginner: [
      { question: "TypeScript adds what to JS?", options: ["HTML", "Types", "CSS", "SQL"], answer: 1 },
      { question: "File extension?", options: [".js", ".ts", ".tp", ".ty"], answer: 1 },
      { question: "Type annotation syntax?", options: ["x: number", "number x", "x as number", "int x"], answer: 0 },
      { question: "Any type means?", options: ["Number", "Skip type checking", "String", "Error"], answer: 1 },
      { question: "Interface defines?", options: ["Function", "Object shape", "Variable", "Loop"], answer: 1 },
      { question: "TS compiles to?", options: ["Java", "Python", "JavaScript", "C++"], answer: 2 },
      { question: "Enum creates?", options: ["Array", "Named constants", "Function", "Class"], answer: 1 },
      { question: "Optional property uses?", options: ["!", "?", "*", "&"], answer: 1 },
      { question: "Type union operator?", options: ["&", "|", "+", "||"], answer: 1 },
      { question: "Readonly prevents?", options: ["Reading", "Modification", "Creation", "Deletion"], answer: 1 },
    ],
    basic: [
      { question: "Generic syntax?", options: ["<T>", "[T]", "{T}", "(T)"], answer: 0 },
      { question: "Type alias uses?", options: ["interface", "type", "typedef", "alias"], answer: 1 },
      { question: "Tuple is?", options: ["Object", "Fixed-length array", "Map", "Set"], answer: 1 },
      { question: "never type means?", options: ["Null", "Unreachable", "Any", "Void"], answer: 1 },
      { question: "Intersection type uses?", options: ["|", "&", "+", "&&"], answer: 1 },
      { question: "as keyword does?", options: ["Import", "Type assertion", "Export", "Define"], answer: 1 },
      { question: "Partial<T> makes?", options: ["All required", "All optional", "All readonly", "All nullable"], answer: 1 },
      { question: "keyof returns?", options: ["Values", "Key union type", "Array", "Object"], answer: 1 },
    ],
    medium: [
      { question: "Conditional type uses?", options: ["if/else", "extends ? :", "switch", "ternary()"], answer: 1 },
      { question: "Mapped type syntax?", options: ["[K in T]", "for K in T", "map(K, T)", "K: T"], answer: 0 },
      { question: "infer keyword is for?", options: ["Variable", "Type inference in conditional", "Import", "Export"], answer: 1 },
      { question: "What is a discriminated union?", options: ["Random union", "Union with common field", "Intersection", "Generic"], answer: 1 },
      { question: "Record<K,V> creates?", options: ["Array", "Object type", "Tuple", "Set"], answer: 1 },
      { question: "What is type narrowing?", options: ["Widening types", "Refining types", "Removing types", "Adding types"], answer: 1 },
    ],
    advanced: [
      { question: "Template literal types use?", options: ["' '", "` `", "\" \"", "/ /"], answer: 1 },
      { question: "What is declaration merging?", options: ["File merge", "Interface combining", "Type deletion", "Import merge"], answer: 1 },
      { question: "What is a type guard?", options: ["Security", "Runtime type check", "Compile error", "Import guard"], answer: 1 },
      { question: "Branded types prevent?", options: ["Imports", "Type confusion", "Exports", "Loops"], answer: 1 },
      { question: "What is covariance?", options: ["Type widening", "Subtype compatibility", "Type removal", "Type creation"], answer: 1 },
      { question: "satisfies operator does?", options: ["Validate type", "Create type", "Delete type", "Cast type"], answer: 0 },
    ],
  },
  php: {
    beginner: [
      { question: "PHP variable prefix?", options: ["@", "#", "$", "&"], answer: 2 },
      { question: "PHP stands for?", options: ["Personal Home Page", "PHP Hypertext Preprocessor", "Pre HTML Processor", "Page Host Protocol"], answer: 1 },
      { question: "Echo does what?", options: ["Input", "Output", "Loop", "Define"], answer: 1 },
      { question: "String concat operator?", options: ["+", ".", "&", "||"], answer: 1 },
      { question: "Array function?", options: ["array()", "new Array()", "[]", "Both A and C"], answer: 3 },
      { question: "PHP runs on?", options: ["Client", "Server", "Both", "Neither"], answer: 1 },
      { question: "Comment syntax?", options: ["// or #", "-- or **", "/* only", "%% only"], answer: 0 },
      { question: "End PHP tag?", options: ["</php>", "?>", "end;", "/>"], answer: 1 },
      { question: "Equality check?", options: ["=", "==", ":=", "eq"], answer: 1 },
      { question: "Function keyword?", options: ["def", "fn", "function", "func"], answer: 2 },
    ],
    basic: [
      { question: "Associative array uses?", options: ["Indexes", "Key-value pairs", "Objects", "Classes"], answer: 1 },
      { question: "Include file with?", options: ["import", "require", "load", "fetch"], answer: 1 },
      { question: "What is $_GET?", options: ["Post data", "URL parameters", "Session", "Cookie"], answer: 1 },
      { question: "foreach loops over?", options: ["Numbers", "Arrays", "Strings only", "Objects only"], answer: 1 },
      { question: "What does isset() check?", options: ["Type", "Variable exists", "Value", "Null"], answer: 1 },
      { question: "PDO is for?", options: ["File I/O", "Database access", "HTML output", "Session mgmt"], answer: 1 },
      { question: "Session starts with?", options: ["session_init()", "session_start()", "start_session()", "new Session()"], answer: 1 },
      { question: "What is Composer?", options: ["IDE", "Package manager", "Server", "Database"], answer: 1 },
    ],
    medium: [
      { question: "Trait is for?", options: ["Inheritance", "Code reuse without inheritance", "Interface", "Abstract class"], answer: 1 },
      { question: "Namespace prevents?", options: ["Errors", "Name collisions", "Loops", "Imports"], answer: 1 },
      { question: "What is PSR-4?", options: ["Security standard", "Autoloading standard", "Coding style", "Database standard"], answer: 1 },
      { question: "Type hinting in PHP?", options: ["Not supported", "function foo(int $x)", "function foo(x: int)", "fn foo<int>()"], answer: 1 },
      { question: "What is middleware?", options: ["Database", "Request/response filter", "Template", "Model"], answer: 1 },
      { question: "Laravel uses which pattern?", options: ["MVVM", "MVC", "MVP", "Flux"], answer: 1 },
    ],
    advanced: [
      { question: "What is a Generator in PHP?", options: ["Class", "Lazy iterator with yield", "Array", "Object"], answer: 1 },
      { question: "Fibers in PHP 8.1 are for?", options: ["Threading", "Cooperative concurrency", "File I/O", "Caching"], answer: 1 },
      { question: "What is Reflection API?", options: ["Mirrors", "Runtime class inspection", "Debugging", "Testing"], answer: 1 },
      { question: "Enum support added in?", options: ["PHP 7", "PHP 8.0", "PHP 8.1", "PHP 5"], answer: 2 },
      { question: "What is Opcache?", options: ["File cache", "Bytecode cache", "Query cache", "Session cache"], answer: 1 },
      { question: "Named arguments use?", options: ["=>", ":", "=", "->"], answer: 1 },
    ],
  },
  numpy: {
    beginner: [
      { question: "NumPy is for?", options: ["Web dev", "Numerical computing", "Database", "Networking"], answer: 1 },
      { question: "Import numpy as?", options: ["num", "np", "ny", "numpy"], answer: 1 },
      { question: "Create array?", options: ["np.array()", "np.list()", "np.create()", "np.new()"], answer: 0 },
      { question: "Array shape returns?", options: ["Length", "Dimensions tuple", "Type", "Sum"], answer: 1 },
      { question: "np.zeros(3) creates?", options: ["[0,0,0]", "[1,1,1]", "[3]", "Error"], answer: 0 },
      { question: "Array dtype is?", options: ["Shape", "Data type", "Size", "Rank"], answer: 1 },
      { question: "np.arange(5) gives?", options: ["1-5", "0-4", "0-5", "1-4"], answer: 1 },
      { question: "Element-wise multiply?", options: ["np.dot()", "a * b", "np.cross()", "a @ b"], answer: 1 },
      { question: "np.ones(2,3) shape?", options: ["(2,)", "(3,2)", "(2,3)", "(6,)"], answer: 2 },
      { question: "What is broadcasting?", options: ["Printing", "Auto shape matching", "Copying", "Sorting"], answer: 1 },
    ],
    basic: [
      { question: "Reshape array with?", options: ["resize()", "reshape()", "transform()", "modify()"], answer: 1 },
      { question: "np.mean() calculates?", options: ["Median", "Average", "Mode", "Sum"], answer: 1 },
      { question: "np.dot() does?", options: ["Element multiply", "Dot product", "Cross product", "Division"], answer: 1 },
      { question: "Slicing a[1:3] gets?", options: ["Elements 1,2", "Elements 1,2,3", "Element 3", "Element 1"], answer: 0 },
      { question: "np.concatenate joins?", options: ["Strings", "Arrays", "Numbers", "Dicts"], answer: 1 },
      { question: "Boolean indexing filters by?", options: ["Index", "Condition", "Type", "Size"], answer: 1 },
      { question: "np.random.rand() range?", options: ["0-100", "-1 to 1", "0 to 1", "Any"], answer: 2 },
      { question: "Transpose with?", options: [".T", ".flip()", ".rotate()", ".swap()"], answer: 0 },
    ],
    medium: [
      { question: "np.linalg.inv() finds?", options: ["Determinant", "Inverse matrix", "Eigenvalues", "Transpose"], answer: 1 },
      { question: "Vectorization means?", options: ["Adding vectors", "Avoiding loops", "Creating arrays", "Sorting"], answer: 1 },
      { question: "np.where() does?", options: ["Search", "Conditional selection", "Sort", "Filter nulls"], answer: 1 },
      { question: "np.stack vs concatenate?", options: ["Same", "Stack adds new axis", "Concatenate adds axis", "No diff"], answer: 1 },
      { question: "Fancy indexing uses?", options: ["Slices", "Integer arrays", "Booleans only", "Strings"], answer: 1 },
      { question: "np.einsum is for?", options: ["String ops", "Einstein summation", "File I/O", "Plotting"], answer: 1 },
    ],
    advanced: [
      { question: "Stride tricks optimize?", options: ["Memory layout", "Sorting", "Printing", "Types"], answer: 0 },
      { question: "np.fft does?", options: ["Filtering", "Fourier Transform", "File ops", "Formatting"], answer: 1 },
      { question: "Memory-mapped arrays use?", options: ["np.memmap", "np.save", "np.load", "np.cache"], answer: 0 },
      { question: "What is contiguous array?", options: ["Sorted", "Sequential memory", "Unique values", "Small array"], answer: 1 },
      { question: "ufunc stands for?", options: ["User function", "Universal function", "Utility function", "Update function"], answer: 1 },
      { question: "np.vectorize does?", options: ["Optimize loops", "Wrap scalar fn for arrays", "Create vectors", "Sort arrays"], answer: 1 },
    ],
  },
  pandas: {
    beginner: [
      { question: "Pandas is for?", options: ["Gaming", "Data analysis", "Web dev", "ML only"], answer: 1 },
      { question: "Import pandas as?", options: ["pa", "pd", "pan", "pandas"], answer: 1 },
      { question: "Main data structure?", options: ["Array", "DataFrame", "Matrix", "Table"], answer: 1 },
      { question: "Read CSV with?", options: ["pd.load()", "pd.read_csv()", "pd.open()", "pd.csv()"], answer: 1 },
      { question: "Select column?", options: ["df.col", "df['col']", "df(col)", "df->col"], answer: 1 },
      { question: "df.shape returns?", options: ["Length", "(rows, cols)", "Type", "Sum"], answer: 1 },
      { question: "df.head() shows?", options: ["Last 5", "First 5 rows", "All rows", "Column names"], answer: 1 },
      { question: "Series is?", options: ["2D data", "1D labeled array", "Matrix", "Dict"], answer: 1 },
      { question: "df.info() shows?", options: ["Data", "Summary info", "Plot", "Stats"], answer: 1 },
      { question: "NaN means?", options: ["Zero", "Missing value", "Error", "Infinity"], answer: 1 },
    ],
    basic: [
      { question: "Filter rows with?", options: ["df.filter()", "df[condition]", "df.where()", "df.select()"], answer: 1 },
      { question: "GroupBy does?", options: ["Sort", "Split-apply-combine", "Filter", "Join"], answer: 1 },
      { question: "df.dropna() removes?", options: ["Duplicates", "NaN rows", "Columns", "Zeros"], answer: 1 },
      { question: "df.merge() is like?", options: ["UNION", "JOIN", "INSERT", "DELETE"], answer: 1 },
      { question: "Apply function with?", options: ["df.map()", "df.apply()", "df.run()", "df.exec()"], answer: 1 },
      { question: "Sort by column?", options: ["df.order()", "df.sort_values()", "df.arrange()", "df.rank()"], answer: 1 },
      { question: "Rename columns with?", options: ["df.rename()", "df.name()", "df.label()", "df.set()"], answer: 0 },
      { question: "Value counts of column?", options: ["df.count()", "df['col'].value_counts()", "df.freq()", "df.tally()"], answer: 1 },
    ],
    medium: [
      { question: "Pivot table creates?", options: ["Chart", "Summary table", "New df", "Index"], answer: 1 },
      { question: "Multi-index is?", options: ["Multiple dfs", "Hierarchical index", "Array index", "String index"], answer: 1 },
      { question: "df.resample() is for?", options: ["Random sampling", "Time series resampling", "Data copy", "Filtering"], answer: 1 },
      { question: "Categorical type saves?", options: ["Time", "Memory", "Accuracy", "Columns"], answer: 1 },
      { question: "df.melt() does?", options: ["Wide to long", "Long to wide", "Sort", "Filter"], answer: 0 },
      { question: "Window function example?", options: ["groupby", "rolling()", "merge()", "concat()"], answer: 1 },
    ],
    advanced: [
      { question: "What is method chaining?", options: ["Importing", "Sequential df operations", "Looping", "Copying"], answer: 1 },
      { question: "df.pipe() is for?", options: ["I/O", "Custom function chains", "Plotting", "Sorting"], answer: 1 },
      { question: "Sparse arrays save?", options: ["Time", "Memory for mostly-null data", "Accuracy", "Types"], answer: 1 },
      { question: "eval() in pandas?", options: ["Run JS", "Efficient string expressions", "Delete", "Copy"], answer: 1 },
      { question: "ExtensionArray is for?", options: ["UI extensions", "Custom data types", "File I/O", "Plotting"], answer: 1 },
      { question: "What is Apache Arrow?", options: ["Web framework", "Columnar memory format", "Database", "API"], answer: 1 },
    ],
  },
  fullstack: {
    beginner: [
      { question: "Frontend runs on?", options: ["Server", "Browser", "Database", "Cloud"], answer: 1 },
      { question: "Backend runs on?", options: ["Browser", "Server", "CSS", "HTML"], answer: 1 },
      { question: "HTTP stands for?", options: ["HyperText Transfer Protocol", "High Tech Transfer", "Host Transfer Protocol", "Hyper Terminal Transfer"], answer: 0 },
      { question: "HTML is for?", options: ["Styling", "Structure", "Logic", "Data"], answer: 1 },
      { question: "CSS is for?", options: ["Logic", "Structure", "Styling", "Data"], answer: 2 },
      { question: "API stands for?", options: ["App Program Interface", "Application Programming Interface", "Auto Program Input", "App Process Integration"], answer: 1 },
      { question: "JSON is?", options: ["Language", "Data format", "Database", "Server"], answer: 1 },
      { question: "URL stands for?", options: ["Uniform Resource Locator", "Universal Reference Link", "User Request Location", "Unified Resource Language"], answer: 0 },
      { question: "GET request does?", options: ["Create data", "Read data", "Update data", "Delete data"], answer: 1 },
      { question: "POST request does?", options: ["Read data", "Create/send data", "Delete data", "Update data"], answer: 1 },
    ],
    basic: [
      { question: "REST stands for?", options: ["Real Estate Software Tech", "Representational State Transfer", "Remote Execution Standard", "Request State Transform"], answer: 1 },
      { question: "Status code 404 means?", options: ["Server error", "Not found", "Success", "Redirect"], answer: 1 },
      { question: "Status code 200 means?", options: ["Error", "Not found", "OK/Success", "Redirect"], answer: 2 },
      { question: "Middleware does?", options: ["Database", "Process between req/res", "Render UI", "Store data"], answer: 1 },
      { question: "CORS is for?", options: ["Caching", "Cross-origin requests", "Compression", "Cookies"], answer: 1 },
      { question: "JWT is for?", options: ["Styling", "Authentication tokens", "Database", "Routing"], answer: 1 },
      { question: "ORM stands for?", options: ["Object Relational Mapping", "Open Resource Manager", "Online Record Model", "Output Request Module"], answer: 0 },
      { question: "MVC stands for?", options: ["Model View Controller", "Main Visual Component", "Module Version Control", "Memory Variable Cache"], answer: 0 },
    ],
    medium: [
      { question: "WebSocket enables?", options: ["File upload", "Real-time bidirectional", "Static pages", "SEO"], answer: 1 },
      { question: "Docker is for?", options: ["Coding", "Containerization", "Testing only", "Design"], answer: 1 },
      { question: "CI/CD stands for?", options: ["Code Integration/Code Delivery", "Continuous Integration/Deployment", "Central Info/Central Data", "Common Interface/Common Design"], answer: 1 },
      { question: "Microservices vs Monolith?", options: ["Same", "Small independent services", "One big app", "No backend"], answer: 1 },
      { question: "Redis is used for?", options: ["SQL database", "In-memory caching", "File storage", "UI framework"], answer: 1 },
      { question: "GraphQL vs REST?", options: ["Same", "Client defines data shape", "Server defines shape", "No API"], answer: 1 },
    ],
    advanced: [
      { question: "Event-driven architecture uses?", options: ["Direct calls", "Message queues", "Polling only", "No communication"], answer: 1 },
      { question: "Horizontal scaling means?", options: ["Bigger server", "More servers", "Less servers", "No change"], answer: 1 },
      { question: "CAP theorem states?", options: ["All 3 always", "Pick 2 of 3", "Pick 1 of 3", "No constraints"], answer: 1 },
      { question: "Rate limiting prevents?", options: ["Slow queries", "API abuse", "Data loss", "UI bugs"], answer: 1 },
      { question: "Blue-green deployment is?", options: ["Color coding", "Zero-downtime deploy", "Testing only", "Backup"], answer: 1 },
      { question: "What is a CDN?", options: ["Central Database Node", "Content Delivery Network", "Cloud Data Network", "Code Deploy Node"], answer: 1 },
    ],
  },
};

export const getChallenges = (language: string, level: string, count = 7): Challenge[] => {
  const lang = language.toLowerCase().replace(/[^a-z+]/g, "");
  const lvl = level.toLowerCase();
  
  const bank = challengeBank[lang]?.[lvl] || challengeBank.python?.beginner || [];
  
  const shuffled = [...bank].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, shuffled.length));
};
